version: '3.3'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/var/www/html